### ISSUE TITLE
[enhancement] COG.YAML support trusted host and extra index for NVIDIA

### ISSUE THREAD

**Issue by djj0s3** [replicate/cog#1006]
Trying to leverage the new TensorRT Diffusers support feature, it requires using NVidia's hosted package manager. My cog.yaml looks like this gross mess:
```
build:
  gpu: true
  cuda: "11.7"
  python_version: "3.9.16"
  system_packages:
    - "python3-pip"
  python_packages:
    - "diffusers==0.15.1"
    - "torch==2.0.0"
    - "ftfy==6.1.1"
    - "scipy==1.9.3"
    - "transformers==4.25.1"
    - "accelerate==0.15.0"
    - "huggingface-hub==0.13.2"
    - "nvidia-pyindex==1.0.9"
    - "tensorrt==8.6.0"
  run: 
    - pip3 install polygraphy --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com
    - pip3 install onnx --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com
    - pip3 install onnx_graphsurgeon --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com
```
Would be great to specify in python_packages to use --extra index and --trusted-host in addition to pypi.

**Comment by mattt** [comment]
Hi @djj0s3. I agree, that's a mess. Fortunately, Cog lets you define package dependencies in a `requirements.txt` file like this:

```yaml
build:
  gpu: true
  cuda: "11.7"
  python_version: "3.9.16"
  system_packages:
    - "python3-pip"
  python_requirements: requirements.txt
```

Then, in a sibling `requirements.txt` file:

```pip
diffusers==0.15.1
torch==2.0.0
ftfy==6.1.1
scipy==1.9.3
transformers==4.25.1
accelerate==0.15.0
huggingface-hub==0.13.2
nvidia-pyindex==1.0.9
tensorrt==8.6.0

--extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com
polygraphy
onnx
onnx_graphsurgeon
```

Unfortunately, this doesn't appear to be documented anywhere. So I opened https://github.com/replicate/cog/pull/1016 to fix that.
