### ISSUE TITLE
Build secrets

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#1009]
This syntax:

```
build:
  run:
    - command: pip install ...
      mounts:
       - type: secret
         id: someid
         target: path/in/container
```

Should turn into:

```
RUN --mount=type=secret,id=someid,target=path/in/container pip install ...
```

then to build you would use:

```
cog build --secret id=someid,src=path/in/host
```

todo:

- [ ] end-to-end documentation on this feature
- [ ] enable feature to work without swarm
- [ ] ensure `cog build` re-builds when contents of secret file changes
