### ISSUE TITLE
Support Cog configuration in `pyproject.toml`

### ISSUE THREAD

**Issue by mattt** [replicate/cog#1082]
Related to #1081

Cog models are Python projects. And as such, they'd benefit from declaring their build system interface with [`pyproject.toml`](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/), and using that to install and configure dev dependencies like [ruff](https://github.com/astral-sh/ruff) and [black](https://github.com/psf/black).

It might be nice to Cog from within a `pyproject.toml` file instead of managing a separate `cog.yaml` file. Here's an example of what that could look like:

```toml
[build-system]
requires = ["cog"]
build-backend = "cog.build"

[project]
name = "cog-stable-diffusion"
description = "An implementation of the Diffusers Stable Diffusion v2.1 as a Cog model"
readme = "README.md"
authors = [{ name = "Replicate", email = "team@replicate.com" }]
license.file = "LICENSE"
urls."Source" = "https://github.com/replicate/cog-stable-diffusion"

# replaces `python_version` field in `cog.yaml`
requires-python = ">=3.8"

# replaces `python_packages` field in `cog.yaml`
dependencies = [
  "diffusers==0.11.1",
  "torch==1.13.0",
  "ftfy==6.1.1",
  "scipy==1.9.3",
  "transformers==4.25.1",
  "accelerate==0.15.0",
  "huggingface-hub==0.13.2",
]

optional-dependencies = { "dev" = [ "black", "cog", "ruff" ] }

# additional settings from `cog.yaml`
[tool.cog]
cuda = "11.6"
```
