### ISSUE TITLE
Building headless colmap (without gui) using cog's yaml file

### ISSUE THREAD

**Issue by Medoalmasry** [replicate/cog#1258]
**Steps to reproduce**
cog build the following yaml file
```
build:
  # set to true if your model requires a GPU
  gpu: true
  cuda: "12.1"

  # a list of ubuntu apt packages to install
  system_packages:
    - "libgl1-mesa-glx"
    - "libglib2.0-0"
    - "git"
    - "cmake"
    - "ninja-build"
    - "build-essential"
    - "libboost-program-options-dev"
    - "libboost-filesystem-dev"
    - "libboost-graph-dev"
    - "libboost-system-dev"
    - "libboost-test-dev"
    - "libeigen3-dev"
    - "libflann-dev"
    - "libfreeimage-dev"
    - "libmetis-dev"
    - "libgoogle-glog-dev"
    - "libgflags-dev"
    - "libsqlite3-dev"
    - "libglew-dev"
    - "qtbase5-dev"
    - "libqt5opengl5-dev"
    - "libcgal-dev"
    - "libceres-dev"
    # - "colmap"
    - "ffmpeg"

  # python version in the form '3.11' or '3.11.4'
  python_version: "3.10"

  # a list of packages in the format <package-name>==<version>
  python_packages:
    # - "torch"
    # - "torchvision"
    # - "torchaudio"
    # - "tensorflow"
    - "pillow"
    - "rembg"
    - "rembg[cli]"

  # commands run after the environment is setup
  run:
    - git clone https://gitlab.com/medoalmasry/headless-colmap.git && cd headless-colmap/build
    - cmake ../CMakeLists.txt -GNinja -DCMAKE_CUDA_ARCHITECTURES=native
    - ninja && ninja install

# predict.py defines how predictions are run on your model
predict: "predict.py:Predictor"
```
**Error Produced:**

```
 > [stage-0 11/14] RUN cmake ../CMakeLists.txt -GNinja -DCMAKE_CUDA_ARCHITECTURES=native:
0.237 CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
0.237 Specify --help for usage, or press the help button on the CMake GUI.
------
Dockerfile:47
--------------------
  45 |     RUN --mount=type=cache,target=/root/.cache/pip pip install -r /tmp/requirements.txt
  46 |     RUN git clone https://gitlab.com/medoalmasry/headless-colmap.git && cd headless-colmap/build
  47 | >>> RUN cmake ../CMakeLists.txt -GNinja -DCMAKE_CUDA_ARCHITECTURES=native
  48 |     RUN ninja && ninja install
  49 |     WORKDIR /src
--------------------
ERROR: failed to solve: process "/bin/sh -c cmake ../CMakeLists.txt -GNinja -DCMAKE_CUDA_ARCHITECTURES=native" did not complete successfully: exit code: 1
ⅹ Failed to build Docker image: exit status 1
```
My reference to building colmap is this [dockerfile](https://github.com/colmap/colmap/blob/dev/docker/Dockerfile):
