### ISSUE TITLE
How to push paddleOCR to Replicate

### ISSUE THREAD

**Issue by adbmdp** [replicate/cog#1682]
Hello,

I'm trying to push my model on Replicate but I got this error :
`ⅹ Failed to get type signature: exit status 132`

Here is my cog.yaml file:
```
build:
  gpu: true

  system_packages:
    - libgl1-mesa-glx

  python_version: "3.11"

  python_packages:
    - pydantic
    - pillow
    - numpy
    - opencv-python
    - paddlepaddle-gpu
    - "paddleocr>=2.0.1"

predict: "predict.py:Predictor"
```

Thanks a lot for any help.
