### ISSUE TITLE
ModuleNotFoundError when using Cog with whisper-at on Docker Desktop for MacOS

### ISSUE THREAD

**Issue by tylerhunter06** [replicate/cog#1732]
**Description:**

I'm trying to deploy a model based on the `whisper-at` library (https://github.com/YuanGongND/whisper-at.git) to Replicate using Cog. I've followed the instructions in the repository's README and made several adjustments to my `cog.yaml` file, but I'm consistently encountering a `ModuleNotFoundError: No module named 'cog'` when running `cog push`.

**Reproduction Steps:**

1. **Environment:**
   - **OS:** macOS Monterey
   - **Cog Version:** [Output of `0.9.9`] 
   - **Python Version:** [Output of `3.12.3`]
   - **Docker Desktop Version:** [`4.30.0` (149282)]

2. **cog.yaml:**

```
build:
  python_version: "3.12.3"
  system_packages:
    - ffmpeg
    - curl
    - build-essential
    - git
  python_packages:
    - cog
  run:
    - apt-get update && apt-get install -y pkg-config libssl-dev
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - bash -c '. $HOME/.cargo/env && pip install tiktoken==0.3.3 && git clone https://github.com/YuanGongND/whisper-at.git && cd whisper-at/package/whisper-at && pip install --no-deps .'  
predict: "predict.py:Predictor"

```
3. **predict.py:**

```
from cog import BasePredictor, Input, Path
import whisper_at as whisper

class Predictor(BasePredictor):
    def setup(self):
        self.model_large = whisper.load_model("large-v1")
        self.model_tiny = whisper.load_model("tiny")
        self.model_tiny_en = whisper.load_model("tiny.en")
        self.model_small = whisper.load_model("small")
        self.mdl_dict = {"tiny": self.model_tiny, "tiny.en": self.model_tiny_en, "small": self.model_small, "large": self.model_large}
        self.lan_dict = {"English": 'en', "Chinese": 'zh'}

    def round_time_resolution(self, time_resolution):
        multiple = float(time_resolution) / 0.4
        rounded_multiple = round(multiple)
        rounded_time_resolution = rounded_multiple * 0.4
        return rounded_time_resolution

    def predict(self, audio_path: Path, model_size: str, language: str, time_resolution: str) -> (str, str):
        audio_tagging_time_resolution = self.round_time_resolution(time_resolution)
        model = self.mdl_dict[model_size]
        if language == 'Auto Detection':
            result = model.transcribe(audio_path, at_time_res=audio_tagging_time_resolution)
        else:
            result = model.transcribe(audio_path, at_time_res=audio_tagging_time_resolution, language=self.lan_dict[language])
        audio_tag_result = whisper.parse_at_label(result, language='follow_asr', top_k=5, p_threshold=-1, include_class_list=list(range(527)))
        asr_output = ""
        for segment in result['segments']:
            asr_output = asr_output + format(segment['start'], ".1f") + 's-' + format(segment['end'], ".1f") + 's: ' + segment['text'] + '\n'
        at_output = ""
        for segment in audio_tag_result:
            at_output = at_output + format(segment['time']['start'], ".1f") + 's-' + format(segment['time']['end'], ".1f") + 's: ' + ', '.join([x[0] for x in segment['audio tags']]) + '\n'
        return asr_output, at_output
```
4. **Command**

```
**Bash**

cog push r8.im/tylerhunter06/whisper-audiotagging
```
5. **Error Message**

```
Validating model schema...

/usr/local/bin/python: Error while finding module specification for 'cog.command.openapi_schema' (ModuleNotFoundError: No module named 'cog')

ⅹ Failed to get type signature: exit status 1
```
6. **Troubleshooting Steps Taken**
-I've verified that the cog package is installed correctly on my host machine.
-added cog to the python_packages section in cog.yaml.
-tried installing cog directly in the run section of cog.yaml.
-confirmed that cog is being installed in the Docker image (checked build logs).
-made sure I'm not using a virtual environment.

**Request**
Could you please investigate this issue? I see that a similar issue was created with #1591, but it's not the exact same. It seems that even though Cog is being installed within the Docker image, it's not being recognized during the model validation step. Any help or insights would be greatly appreciated.
