### ISSUE TITLE
No concrete output on invalid cog yaml

### ISSUE THREAD

**Issue by 8W9aG** [replicate/cog#1826]
If I use a `cog.yaml` like so:

```yaml
build:
  gpu: true
  cuda: "11.8"
  python_version: "3.11"
  python_packages:
    - "torch==2.0.1"

predict: "predict.py:Predictor"
concurrency: 54
```

I receive the following message:

```
ⅹ There is a problem in your cog.yaml file. 
ⅹ must be a mapping.
ⅹ 
ⅹ To see what options you can use, take a look at the docs:
ⅹ https://github.com/replicate/cog/blob/main/docs/yaml.md
ⅹ 
ⅹ You might also need to upgrade Cog, if this option was added in a
ⅹ later version of Cog.
```

I believe that the output should say "concurrency must be a mapping" but instead this value is being erased from the errors output.
