### ISSUE TITLE
Feature request - specify python base image

### ISSUE THREAD

**Issue by luarss** [replicate/cog#1988]
I am building my image using the command: `cog build -t model:latest --use-cog-base-image=false --separate-weights` but I face an error while parsing. Would it be a good feature to consider for slimmer images?

```
ⅹ invalid Python version format: strconv.Atoi: parsing "11-slim": invalid syntax
```

Sample cog.yaml I am using:
```
build:
  gpu: true
  system_packages:
    - "ffmpeg"
  python_version: "3.11-slim"
  python_packages:
    - "torch==2.3.0"
predict: "predict.py:Predictor"
```

Other info
- Cog 0.9.20
