### ISSUE TITLE
Base image cuda12.4-python3.12-torch2.5.1 ffmpeg is missing

### ISSUE THREAD

**Issue by bzikst** [replicate/cog#2121]
Config with base image `r8.im/cog-base:cuda12.4-python3.12-torch2.5.1` seems to be missing ffmpeg. Adding it in system_packages wont help — I think because cog is removing ffmpeg from deps and assumes all base images already have it. 

I'm using this command to build
`cog build --separate-weights --use-cog-base-image`

The workaround I use for now is run section:
`--mount=type=cache,target=/var/cache/apt,sharing=locked apt-get update -qq && apt-get install -qqy ffmpeg && rm -rf /var/lib/apt/lists/*`

**Comment by 8W9aG** [comment]
I've added this integration test: https://github.com/replicate/cog/pull/2122
It seems to be passing, which I believe means that a fix we made previously solves this, we just need to re-release cog. I will cut a new release tomorrow which should sort this out for you.

**Comment by 8W9aG** [comment]
Alright just released `0.13.7` let me know if this is solving your problem. Re-open the issue if it isn't the case.

**Comment by bzikst** [comment]
Unfortunatelly, 0.13.7 release changed nothing to me in this case. I've reproduced integration test you've added and it works ok with Python 3.9 and failes with Python 3.12.

Can you please try this cog.yaml?

```
build:
  gpu: true
  python_version: "3.12"
  python_packages:
    - "torch==2.5.1"
  cuda: "12.4"
  run:
    - command: ffmpeg --help
predict: "predict.py:Predictor"
```

It uses `r8.im/cog-base:cuda12.4-python3.12-torch2.5.1` and outputs `/bin/sh: 1: ffmpeg: not found`
