### ISSUE TITLE
Copy files to use in `run` commands

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#223]
`run` commands in `cog.yaml` can't use any of the user's files. It would be neat to allow this, in a way that could still be cached. Maybe you could define what files need copying somehow?

```
build:
  run:
    - copy: "foo.txt"
      command: "echo foo.txt"
```
