### ISSUE TITLE
[Build] Title: ONNX Runtime Cannot Detect GPU on A100 with CUDA 12.4

### ISSUE THREAD

**Issue by oto-tatsuu** [replicate/cog#2241]
### Description:
I am deploying my model on Replicate, and I found that ONNX Runtime cannot detect the GPU on the machine. My environment includes:

GPU: A100
Python: 3.12
CUDA: 12.4

Here is my cog.yaml configuration:

```
# cog.yaml
build:
  gpu: true
  cuda: "12.2"
  system_packages:
    - "ffmpeg"
  python_version: "3.12"
  python_requirements: "requirements.txt"

  run:
    - "echo env is ready!"
image: "r8.im/mico-world/facefusion"
predict: "predict.py:Predictor"
```
```
# requirements.txt
filetype==1.2.0
gradio==5.9.1
gradio-rangeslider==0.0.8
numpy==2.2.0
onnx==1.17.0
onnxruntime==1.20.1
onnxruntime-gpu==1.20.1
opencv-python==4.10.0.84
psutil==6.1.1
tqdm==4.67.1
scipy==1.14.1
Jinja2==3.1.5
```

However, when I run:
`nvcc --version` It returns CUDA 12.4, while `nvidia-smi` shows CUDA 12.2.

I suspect that this version mismatch is causing ONNX Runtime to fail in recognizing the GPU.
I attempted to change the CUDA version in cog.yaml to 12.2, but it resulted in the following error:

`ERROR: failed to solve: failed to resolve source metadata for r8.im/cog-base:cuda12.2-python3.12: r8.im/cog-base:cuda12.2-python3.12: not found`. It seems that there is no available base image for CUDA 12.2 with Python 3.12.

Would appreciate any guidance on resolving this issue. Thank you!
