### ISSUE TITLE
Cog malformed requirements.txt

### ISSUE THREAD

**Issue by dsinha244** [replicate/cog#2280]
Following is my requirements.txt file

[requirements.txt](https://github.com/user-attachments/files/19897527/requirements.txt)

This is my cog file

```
build:
  system_packages:
    - "libgl1-mesa-glx"
    - "libglib2.0-0"
    - wget
  python_version: "3.10"
  python_requirements: "lib/requirements.txt"
  run:
    - wget -q https://storage.googleapis.com/labelbox-assets/clip_market1501.pt
    - python -c 'from boxmot import DeepOCSORT;from pathlib import Path;DeepOCSORT(model_weights=Path("clip_market1501.pt"), device="cpu", fp16=False)'
predict: "aws_rekognition.py:AWSRekognition"

```
When i run cog build it is erroring out with the following message
```

9.21 ERROR: Could not find a version that satisfies the requirement ython_version<"3.13" (from versions: none)
19.21 ERROR: No matching distribution found for ython_version<"3.13"
19.23 
19.23 [notice] A new release of pip is available: 23.0.1 -> 25.0.1
19.23 [notice] To update, run: pip install --upgrade pip
```
Upon further inspection when i check the requirements.txt file in .cog/tmp/build.****. I see a malformed requirements.txt as follows

```
--extra-index-url https://download.pytorch.org/whl/cpu
annotated-types==0.7.0
anyio==4.8.0
asttokens==2.4.1
attrs==22.2.0
backports-tarfile==1.2.0
beautifulsoup4==4.13.3
build==1.2.2.post1
cachecontrol==0.14.2
cachetools==5.5.2
certifi==2025.1.31
cffi==1.17.1
charset-normalizer==3.4.1
cleo==2.1.0
click==8.1.8
cog==0.14.7
colorama==0.4.6
crashtest==0.4.1
cryptography==43.0.3
decorator==5.2.1
deepmerge==1.1.1
devtools==0.12.2
distlib==0.3.9
distro==1.9.0
dulwich==0.22.8
exceptiongroup==1.2.2
executing==2.2.0
fastapi==0.115.11
fastjsonschema==2.21.1
filelock==3.18.0
findpython==0.6.3
google-api-core==1.34.1
google-auth==2.38.0
google-cloud-secret-manager==2.16.4
google-crc32c==1.6.0
googleapis-common-protos==1.69.0
grpc-google-iam-v1==0.14.1
grpcio-status==1.48.2
grpcio==1.70.0
h11==0.14.0
httpcore==1.0.7
httptools==0.6.4
httpx==0.28.1
idna==3.10
importlib-metadata==8.6.1
iniconfig==2.0.0
installer==0.7.0
jaraco-classes==3.4.0
jaraco-context==6.0.1
jaraco-functools==4.1.0
jeepney==0.9.0
jiter==0.8.2
keyring==25.6.0
levenshtein==0.24.0
ython_version < "3.13"
more-itertools==10.6.0
msgpack==1.1.0
numpy==1.26.4
openai==1.65.4
packaging==24.2
pbs-installer==2025.4.9
pillow==11.1.0
pkginfo==1.12.1.2
platformdirs==4.3.7
pluggy==1.5.0
poetry-core==2.1.2
poetry-plugin-export==1.9.0
poetry==2.1.2
proto-plus==1.26.0
protobuf==3.20.3
py==1.11.0
pyasn1-modules==0.4.1
pyasn1==0.6.1
pycparser==2.22
pydantic-core==2.27.2
pydantic==2.10.6
pygments==2.19.1
pypdf==4.3.1
pyproject-hooks==1.2.0
pytest==7.4.4
python-dotenv==1.0.1
python-levenshtein==0.24.0
pywin32-ctypes==0.2.3
pyyaml==6.0.2
rapidfuzz==3.12.2
regex==2024.11.6
requests-toolbelt==1.0.0
requests==2.32.3
retry==0.9.2
rsa==4.9
secretstorage==3.3.3
shellingham==1.5.4
six==1.17.0
sniffio==1.3.1
soupsieve==2.6
starlette==0.46.0
structlog==24.4.0
tiktoken==0.7.0
tomli==2.2.1
tomlkit==0.13.2
tqdm==4.67.1
trove-classifiers==2025.3.19.19
typing-extensions==4.12.2
urllib3==1.26.20
uvicorn==0.34.0
uvloop==0.21.0
virtualenv==20.30.0
watchfiles==1.0.4
version < "3.13"
websockets==15.0
xattr==1.1.4
zipp==3.21.0
zstandard==0.23.0
boto3==1.33.12
torch==2.2.1
numpy==1.26.4
boxmot==10.0.79
opencv-python==4.7.0.72
```
Notice the malformed `ython_version < "3.13"`  and `version < "3.13"` lines in the file. Using cog cli (0.14.7). Anyone has any idea what is going on?
