### ISSUE TITLE
[Bug] requirements.txt incorrect parsing

### ISSUE THREAD

**Issue by Runist** [replicate/cog#2357]
## Problem
The problem is, when I run : "cog predict -i face_image=@./input.png", it start build image. And error will occur certain package.
![Image](https://github.com/user-attachments/assets/d48ee31f-0c2a-4c42-a998-f11bb196258f)
It seem like install requirement package with incorrect parsing.

## requirements.txt
```
...
rsa==4.9.1
s3transfer==0.10.4
safetensors==0.5.3
scikit-image==0.24.0
scikit-learn==1.6.1
scipy==1.15.3
seaborn==0.13.2
segment-anything==1.0
sentencepiece==0.2.0
sentry-sdk==2.28.0
setproctitle==1.3.6
...
```

## cog.yaml
```
# Configuration for Cog ⚙️
# Reference: https://cog.run/yaml

build:
  # set to true if your model requires a GPU
  gpu: true
  cuda: "12.4"
  
  # a list of ubuntu apt packages to install
  # system_packages:
  #   - "libgl1-mesa-glx"
  #   - "libglib2.0-0"

  # python version in the form '3.11' or '3.11.4'
  python_version: "3.10.16"

  # path to a Python requirements.txt file
  python_requirements: requirements.txt

  # commands run after the environment is setup
  # run:
  #   - "echo env is ready!"
  #   - "echo another command if needed"

# predict.py defines how predictions are run on your model
predict: "predict.py:Predictor"

```

## Environment
- Ubuntu 24.10
- GPU: RTX 6000 Ada
- 32GB

## Background
The project is base on ComfyUI, I have a workflow which export python code(image_gen.py). I want to push it to replicate. So I build a new empty conda env, and install necessary python package. When I run my code(image_gen.py), it can get correct result. And I run "pip freeze > requirements.txt" to get all package information.
