### ISSUE TITLE
Is python_requirements in cog.yaml still a thing?

### ISSUE THREAD

**Issue by zeke** [replicate/cog#270]
I've got a `cog.yaml` from a few months ago that looks like this:

```yml
model: "predict.py:AnimalVisionModel"
environment:
  python_version: "3.8"
  python_requirements: "requirements.txt"
```

I don't see anything about `python_requirements` in the docs, but I do see some lingering [references to it in the codebase](https://github.com/replicate/cog/search?q=python_requirements).

Let's consider documenting it or removing it, if possible.
