### ISSUE TITLE
Environment variables in cog.yaml

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#291]
Cog should have an equivalent to the Dockerfile `ENV` stanza or the Docker Compose `environment` option.

Like this:

```yaml
build:
  environment:
    MY_VAR: my_value
```
