### ISSUE TITLE
Throw error if invalid keys exist in cog.yaml

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#34]
Currently invalid keys are silently ignored.

For example, a `cog.yaml` that contains this:

```
buildd:
  python_version: "3.8"
  python_packages:
    - "torch=1.8.0"
```

Will silently not install `torch`, instead of complaining that the key `buildd` doesn't exist.

## Future

We may also want to validate the values at some point. For example, ensuring `python_version` is a string and matches a given pattern. (If you omit the quotes, `3.1` and `3.10` are indistinguishable! Thanks YAML!)

(Edited by @andreasjansson and @bfirsh.)
