### ISSUE TITLE
Cog couldn't automatically determine a CUDA version

### ISSUE THREAD

**Issue by mitchellgordon95** [replicate/cog#390]
Doing cog run with the following cog.yaml:

```
image: "myimage"
build:
  gpu: true
  python_version: "3.8"
  python_packages:
    - "torch==1.10.1"
```

yields an error message

```
ⅹ Cog couldn't automatically determine a CUDA version for torch==1.10.1. You need to set the 'cuda' option in cog.yaml to set what version to use. You might be able to find this out from https://pytorch.org/
```

Same for `torch==1.9.0`. Obviously I can set the CUDA myself, but I'm not supposed to have to, right?
