### ISSUE TITLE
Cog install wrong pytorch version when cuda is specified

### ISSUE THREAD

**Issue by dashstander** [replicate/cog#436]
### cog version: 0.0.20

With this minimal __cog.yaml__ I run into problems.

```
build: 
    gpu: true
    cuda: "11.3"
    python_version: "3.8"
    python_packages:
        - "torch==1.10.2"
        - "torchvision==0.11.3"
```

The image builds without error, just a warning about being unsure whether cuda and pytorch match. However, this matches the pytorch [recommended installation versions](https://pytorch.org/get-started/locally/) as of 2022/02/22 which is to run `pip3 install torch==1.10.2+cu113 torchvision==0.11.3+cu113 torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`.

However, once the image is built I cannot actually use the GPU, the issue being that running:

`cog run python -c "import torch; print(torch.__version__)"` 

gives me "1.10.2+cu102", and cuda 10.2 is not compatible with the architecture of the 3090.

To get around this I added the command pytorch recommends above directly to the `run` section of the __cog.yaml__, which works but is very clunky.
