### ISSUE TITLE
Specify what GPUs a model is compatible with and check compatibility on boot

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#505]
Something like this:

```
build:
  gpu:
    ram: 16gb
    models:
     - p100
```

When the model boots up, it can run `nvidia-smi` or whatever and determine whether it is in a compatible environment. It could either fail hard or just warn, or have some way of saying "I know what I'm doing".
