### ISSUE TITLE
Ability to define dev dependencies

### ISSUE THREAD

**Issue by iperdomo** [replicate/cog#565]
In line with my comment on https://github.com/replicate/cog/issues/560#issuecomment-1106075891=, I'm opening a different issue to consider the possibility to define  `development` and `production` dependencies. I would consider adding `jupyterlab` as _dev_ dependency but I wouldn't like to have it as part of the production/deployed image.

### Idea

* Use multi-stage build, starting with `production` and a different one for `development`, you can use the feature to _stop at_ a particular stage. Relevant documentation: https://docs.docker.com/develop/develop-images/multistage-build/#stop-at-a-specific-build-stage

### Example
```yaml
build:
  python_version: "3.8"
  python_packages:
    production:
      - "numpy==1.19.4"
    development:
      - "jupyterlab==3.3.4"
predict: "predict.py:Predictor"
```
or a different key to not introduce backward incompatible changes
```yaml
build:
  python_version: "3.8"
  python_packages:
    - "numpy==1.19.4"
  python_packages_development:
    - "jupyterlab==3.3.4"
predict: "predict.py:Predictor"

```
Produced `Dockerfile` would be something like:

```Dockerfile
# syntax = docker/dockerfile:1.2

# production
FROM python:3.8 AS production
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu:/usr/local/nvidia/lib64:/usr/local/nvidia/bin
COPY .cog/tmp/build1779781291/cog-0.0.1.dev-py3-none-any.whl /tmp/cog-0.0.1.dev-py3-none-any.whl
RUN --mount=type=cache,target=/root/.cache/pip pip install /tmp/cog-0.0.1.dev-py3-none-any.whl
RUN --mount=type=cache,target=/root/.cache/pip pip install   numpy==1.19.4
WORKDIR /src
EXPOSE 5000
CMD ["python", "-m", "cog.server.http"]
COPY . /src

# development
FROM python:3.8 AS development
RUN --mount=type=cache,target=/root/.cache/pip pip install   jupyterlab==3.3.4
```

When running the image via `cog run` it would use the `development` stage. But when running the `cog build` it would stop at `production` stage via `--target`, e.g. `docker build --target production -t <tag> .`

The whole idea is to reduce the size of the image deployed to production.
