### ISSUE TITLE
Tensorflow is erased from python_packages and not installed

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#710]
The following cog.yaml will _not_ install any version of tensorflow:

```
build:
  gpu: true
  cuda: "11.6.2"
  python_version: "3.10"
  python_packages:
    - "diffusers==0.2.4"
    - "torch==1.12.1 --extra-index-url=https://download.pytorch.org/whl/cu116"
    - "ftfy==6.1.1"
    - "scipy==1.9.0"
    - "transformers==4.21.1"

    # FILM requirements
    - "tensorflow==2.8.0"
    - "tensorflow-datasets==4.4.0"
    - "tensorflow-addons==0.16.1"
    - "absl-py==0.12.0"
    - "gin-config==0.5.0"
    - "parameterized==0.8.1"
    - "mediapy==1.0.3"
    - "scikit-image==0.19.1"
    - "gdown==4.4.0"

  run:
    - "git clone https://github.com/google-research/frame-interpolation.git /frame-interpolation"

predict: "predict_animate.py:Predictor"
image: "r8.im/andreasjansson/stable-diffusion-animation"
```

However, when I add `pip install tensorflow==2.8.0` to `run:` it works.

My guess is that something in the CUDA compatibility logic is breaking.
