### ISSUE TITLE
Pick latest CUDA version when specifying patch version

### ISSUE THREAD

**Issue by bfirsh** [replicate/cog#813]
```
build:
  python_version: "3.10"
  cuda: "11.6"
  python_packages:
   - "torch==1.13.0"
```

This automatically selects CUDA 11.6.0 for the base image. It should pick the latest patch version and use 11.6.2.
