### ISSUE TITLE
Could not find a version that satisfies the requirement `torch==1.11.0+cu113`

### ISSUE THREAD

**Issue by cameronk** [replicate/cog#814]
Looking to set up [pyannote-audio](https://github.com/pyannote/pyannote-audio#installation) with a specific version of `torch`.

```
build:
  gpu: true
  python_version: "3.8"
  python_packages:
    - "pyannote.audio==2.1.1"
    - "torch==1.11.0"
    - "torchaudio==0.11.0"
    - "torchvision==0.12.0"
  system_packages:
    - "libsndfile1"
predict: "predict.py:Predictor"
```

```
 > [stage-0 8/9] RUN --mount=type=cache,target=/root/.cache/pip pip install   pyannote.audio==2.1.1 torch==1.11.0+cu113 torchaudio==0.11.0 torchvision==0.12.0+cu113:
#14 0.922 Collecting pyannote.audio==2.1.1
#14 0.926   Using cached pyannote.audio-2.1.1-py2.py3-none-any.whl (390 kB)
#14 1.011 ERROR: Could not find a version that satisfies the requirement torch==1.11.0+cu113 (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0)
#14 1.016 WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
#14 1.016 You should consider upgrading via the '/root/.pyenv/versions/3.8.15/bin/python3.8 -m pip install --upgrade pip' command.
```

I believe the warning at the end may be relevant, it looks it may have been recently fixed pypa/pipenv#5022
