### ISSUE TITLE
Failed to build Docker image: exec: "docker": executable file not found in $PATH

### ISSUE THREAD

**Issue by RationalChestnut** [replicate/cog#860]
Just cloned anythingv3.0 off of Replicate and am attempting to run it on my computer. After cloning the repository, I am running the command `cog run script/download-weights` but receive the error: "Building Docker image from environment in cog.yaml...
ⅹ Failed to build Docker image: exec: "docker": executable file not found in $PATH"

First time doing this. Not quite sure what to do. 

Here is what the cog.yaml file looks like:
```
build:
  gpu: true
  python_version: "3.10"
  python_packages:
    - "diffusers==0.11.0"
    - "torch==1.13.0"
    - "ftfy==6.1.1"
    - "scipy==1.9.3"
    - "transformers==4.25.1"
    - "accelerate==0.15.0"

predict: "predict.py:Predictor"
```
