### ISSUE TITLE
Base image marked for deletion

### ISSUE THREAD

**Issue by andreasjansson** [replicate/cog#863]
Cog's base images need updating.

Given the following config:

```
build:
  cuda: "11.4"
  gpu: true
  system_packages:
    - ffmpeg
  python_packages:
    - numpy==1.24.1
    #- sacred==0.8.2
    - tqdm==4.64.1
    - librosa==0.9.2
    - matplotlib==3.6.2
    - torch==1.13.1
    - torchaudio==0.13.1
    - matplotlib==3.6.2
```

...this error is reported:

```
*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
```
